# Managed by salt stack
wpd-deploy () { echo "Going to update roles for:"; sudo salt -G "roles:$@" grains.get roles; echo "Deploying..."; sudo salt -G "roles:$@" state.sls code; }
alias wpd-flavor="nova flavor-list"
alias wpd-secgroup="nova secgroup-list"
