scaler-packages:
  pkg.installed:
    - pkgs:
      - imagemagick
      - ffmpeg2theora
      - librsvg2-bin
      - djvulibre-bin
      - netpbm
      - gsfonts
      - xfonts-scalable
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-base
      - xfonts-mplus
      - ttf-liberation
      - ttf-ubuntu-font-family
      - libogg0
      - libvorbisenc2
      - libtheora0
      - oggvideotools
      - libvips-tools
      - fonts-linuxlibertine
