description "Hypothesis server"

start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]

script
   cd /srv/webplatform/h
   #export SCRIPT_NAME='/notes'
   # https://lukedrummond.net/2014/02/django-with-prefix-nginxgunicorndjango/
   # http://albertoconnor.ca/blog/2011/Sep/15/hosting-django-under-different-locations
   ./bin/hypothesis serve h.ini
end script
