#
# Lumberjack IRC channel listener
#
# file: /etc/init/lumberjack.conf
# salt: bots/files/lumberjack.init
#
description "Lumberjack IRC logger daemon"

start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]

respawn
setuid renoirb
setgid deployment

script
  logger "Starting IRC logger LumberJack"
  cd /srv/webplatform/lumberjack-listener
  exec /usr/bin/python LumberJack.py
end script
