#!upstart
description "Firefox Accounts Profile server"

# See also http://howtonode.org/deploying-node-upstart-monit

start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]

script
   cd /srv/webplatform/auth/fxa-profile-server
   export CONFIG_FILES=./config/prod.json
   export NODE_ENV=prod
   exec su -s /bin/bash -c '/usr/bin/nodejs bin/server.js' ubuntu >> /var/log/fxa/fxa-profile-server.log 2>&1
end script
