#!upstart
description "Firefox Accounts Authentication server"

start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]

script
   cd /srv/webplatform/auth/fxa-auth-server
   export CONFIG_FILES=./config/prod.json
   exec su -s /bin/bash -c 'scripts/start-local.sh 2>&1 | bunyan -o short' {{ svc_user }} >> /var/log/fxa/fxa-auth-server.log 2>&1
end script
