#!upstart
description "Firefox Accounts Content server"

# See also http://howtonode.org/deploying-node-upstart-monit

start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]

script
   cd /srv/webplatform/auth/fxa-content-server
   exec su -s /bin/bash -c 'node_modules/grunt-cli/bin/grunt server:dist --force' ubuntu >> /var/log/fxa/fxa-content-server.log 2>&1
end script
