# http://docs.docker.com/compose/
# https://github.com/cachethq/Cachet/blob/master/Dockerfile

FROM cachethq/cachet

WORKDIR /var/www/html/

RUN php artisan key:generate

# to run:
#   - docker-compose up -d

